# Generated by Django 3.0.4 on 2020-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaptcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
